# Generated by Django 5.1.3 on 2024-12-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historic',
            old_name='username',
            new_name='user',
        ),
    ]
